name: Cloud Run

on:
  push:
    branches: [ master ]

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ github.event.repository.name }}:${{ github.sha }}
  REGION: asia-northeast1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker
      - run: docker build -t $IMAGE .
      - run: docker push $IMAGE
      - run: gcloud run deploy $SERVICE_NAME --image $IMAGE --region $REGION --platform managed --update-env-vars ${{ secrets.ENV_VARS }}
